FROM python:3.6.6-alpine
LABEL maintainer 'Marcelo Moraes <marcelo.moraes at geru.com.br>'
RUN mkdir src
COPY requirements.txt /
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip3 install -r requirements.txt
COPY /docker_pratica /src/

WORKDIR /src

CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]

EXPOSE 80